### ISSUE TITLE
The two adaptivity variants work with different data at the start of the time window

### ISSUE THREAD

**Issue by IshaanDesai** [precice/micro-manager#132]
In the current implementation, we offer two variants of how the adaptivity is computed: 

1. Compute the adaptivity at the start of every time window
2. Compute the adaptivity in every iteration of every time window

In the time loop the following operations are done:

1. Adjust the time step size
2. Write a checkpoint
3. If adaptivity computation variant 1 is selected, compute the adaptivity immediately after writing a checkpoint
4. Read data from preCICE
5. If adaptivity computation variant 2 is selected, compute the adaptivity

The problem here is that for variant 2, the adaptivity uses the newly read macro-scale data. Variant 1 on the other hand uses the old macro-scale data. In my opinion this is inconsistent.

@mathiskelm @Fujikawas opinions?

**Comment by Fujikawas** [comment]
> In the end we want to use the best available data. 

I fully agree. 
From this point, I think even when the macro-scale is the first participant and the micro-scale would read in some non-converged data, these data are still useful for the adaptivity calculation. They contain information about the problem in the latest time window. So to do step 3 after data reading makes more sense for me.
And for variant 2 the current sequence is correct.

**Comment by IshaanDesai** [comment]
> If switching behavior based on participant order is not desirable, always using the previous data should be preferable, since the macro data didn't change much from the penultimate to last iteration (convergence criterion reached).

Such switching behavior could possibly be coded in, but in a hacky way. However I doubt how much *benefit* there is in using the most correct (in the sense of convergence) data from the previous time window. I agree that for variant 1, we should stick to using the converged macro data of the last time window.

> for variant 1 the current behavior is the preferable default but delaying adaptivity computation to step 5 would be better if the micro-manager is the first participant in the preCICE coupling.

Why would delaying the adaptivity computation for variant 1 when the Micro manager is the participant be beneficial? Would we not read the same data from the macro participant as we did in the last iteration of the last time window?
