### ISSUE TITLE
Allow user to provide comparison function for similarity calculation in adaptivity

### ISSUE THREAD

**Issue by IshaanDesai** [precice/micro-manager#24]
Currently the adaptivity calculates similarity between two simulations based on an absolute difference:

https://github.com/precice/micro-manager/blob/cec8910d8cefbdb32465b520821e9a1069219414/micro_manager/adaptivity.py#L59-L62

Instead of doing an absolute difference, the user can provide a function of their choice to use in the similarity computation. Alternatively the manager can provide various options for the user to pick from.

**Comment by erikscheurer** [comment]
What options would be appropriate for this kind of distance comparison? Since the L1 distance is currently implemented, L2 would be an additional suggestion but adding more should be straight forward in #40.

**Comment by IshaanDesai** [comment]
Discussed on call with @erikscheurer and we plan to provide four options:

- absolute L1 norm
- relative L1 norm
- absolute L2 norm
- relative L2 norm
