### ISSUE TITLE
Add documentation of the Micro Manager to precice.org

### ISSUE THREAD

**Issue by IshaanDesai** [precice/micro-manager#31]

**Comment by erikscheurer** [comment]
Should the documentation be just the Readme or should we create a `docs/` folder as eg in the [openFOAM adapter](https://github.com/precice/openfoam-adapter/tree/develop/docs)?
In my opinion it should be fine at the moment, but it is starting to get a bit crammed and splitting for example the installation, setup, adaptivity and other languages might be more future proof.

**Comment by IshaanDesai** [comment]
Discussed via call with @erikscheurer and we will split the documentation into subsections to increase readability.
