### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by mbkumar** [precice/micro-manager#62]
The latest release version for libprecice is v2.5.0, so based on the documentation on precice website, I can only install pyprecice=v2.5.0 because of its dependency on libprecice. And micromanager depends on pyprecice>=v3.0dev2. How can this incompatibility be addressed?

**Comment by IshaanDesai** [comment]
Hi @mbkumar 

The documentation on the preCICE website is based on preCICE v2.5.0, but the documentation for the Micro Manager is for its use with the latest [develop](https://github.com/precice/precice/tree/develop) branch of preCICE. We are aware that this is not in sync, but did this to have at least some documentation of the Micro Manager on the preCICE website, and then it did not make sense to write *old* documentation. preCICE v3.0.0 will be released in the near future, and the documentation will sync up again.

If you install Micro Manager [v0.3.0](https://github.com/precice/micro-manager/releases/tag/v0.3.0), pip will install pyprecice v2.5.0.4, and you will have a software stack compatible with preCICE v2.5.0.

You may wonder why we released v0.3.0 of the Micro Manager to be compatible with preCICE v2.5.0, when we already had a much more updated code of the Micro Manager. We did this precisely to have a stable released version to be compatible with preCICE v2.5.0 before moving on to preCICE v3.0.0 related development.
