### ISSUE TITLE
Add functionality for spanshot computation from a full-order model

### ISSUE THREAD

**Issue by IshaanDesai** [precice/micro-manager#89]
In the framework of the [SimTech project PN5-9(II)](https://www.simtech.uni-stuttgart.de/exc/research/pn/pn5/pn5-9ii/) the Micro Manager needs to be extended to be able to do an offline snapshot computation step for a given full-order model. The input parameter space for creating the snapshots will be defined by the user through a configuration file. The existing JSON file could be potentially used for this, or a new configuration file format can be explored. The data required from the simulations (output) is also defined by the user. The database developed from this computation should have an interface between its output and the reduced-order/surrogate models, presumably using [hdf5](https://github.com/HDFGroup/hdf5). Rough tasks to add this functionality are:

- [x] Design configuration options for parameter space and data output options to run a full-order model
- [x] Finalize a file format for configuring the parameters of the snapshot computation
- [x] Implement a new class in the Micro Manager to run the offline computation
- [x] Find the most suitable file format to store the snapshots and create an interface to surrogate/reduced-order models
- [x] For a simple dummy simulation, try to output the snapshots in the file format finalized in the previous step

**Comment by uekerman** [comment]
And (advanced)
- [ ] Provide a callback interface to call any user-provided (Python?) post-processing script

**Comment by IshaanDesai** [comment]
Closed via https://github.com/precice/micro-manager/pull/101
