### ISSUE TITLE
Output runtime for calculation of similarity

### ISSUE THREAD

**Issue by steffenger** [precice/micro-manager#91]
For really fast microsimulations (PDE-ODE), the calculation of similarity could be as costly as the runtime of the microsimulations itself (micro_sim_time). I think it makes sense to be able to compare the two variables as a user, since the calculation of similarity probably also depends on multiple factors.

I could also imagine a feature where the micro-manager decides by itself if adaptvitiy should be used or not by comparing runtime of microsimulations vs calculation of similarity.

**Comment by IshaanDesai** [comment]
The first step here would be to output the exact runtime of the adaptivity calculation. This is straightforward. Using the runtime information to make decisions on-the-fly is a more advanced step.
