### ISSUE TITLE
Handling of BoundingBox for Receiving Mesh compared to preCICE API

### ISSUE THREAD

**Issue by steffenger** [precice/micro-manager#97]
In the [couple your code section](https://precice.org/couple-your-code-direct-access.html) the Bounding Box is defined by two corners.

```
std::vector<double> boundingBox {
        0, 0, 0, // minimum corner
        1, 1, 1 // maximum corner
    };
```

While the [macro domain bounds](https://precice.org/tooling-micro-manager-configuration.html) are defined that way
 
```
[xmin, xmax, ymin, ymax, zmin, zmax]

```

I was wondering why the two are not the same:D

**Comment by uekerman** [comment]
The Python API below. I guess there is some conversion happening.

https://github.com/precice/python-bindings/blob/461a6fadbebf4a74a7ee1fd3882b3d75d5eefcca/cyprecice/cyprecice.pyx#L957-L1011

**Comment by IshaanDesai** [comment]
> The Python API below

Good point mentioning the Python API here. In the Micro Manager configuration, I would tend to remain consistent with the Python API of preCICE rather than the C++ API, as it is a tool which relies on the Python bindings.
